[settings]
# missing_runtime_behavior = "autoinstall"
trusted_config_paths = ["~/Projects", "~/Work"]
legacy_version_file = true
status.missing_tools = "always"

[tools]
neovim = "0.12.1"
node = "latest"
prettier = "3.8.1"
rust = "stable"
tree-sitter = "0.26.8"
"cargo:cargo-binstall" = "latest"
"cargo:dioxus-cli" = "latest"
python = "3.14.5"
usage = "latest"
