hostname: "{{ machine }}"
---
when: os in ["macos", "linux"]

files:
  - source: home
    destination: ~/
    link_files: true

git.repo:
  - source: https://github.com/ohmyzsh/ohmyzsh.git
    destination: ~/.oh-my-zsh

sudoers:
  mode: passwordless
  defaults: |
    # Don't keep HOME (that's super obnoxious)
    Defaults env_keep -= "HOME"
    # But do keep PATH so we can run our commands as root
    Defaults exempt_group = {{ user }}

shell.values:
  - destination: ~/.shared_profile.d/nk-vars
    values:
      DOTFILES_MACHINE: "{{ machine }}"
    export: true

link-cleanup:
  - ~/.config/alacritty
  - ~/.config/gh
  - ~/.config/git
  - ~/.config/mise
  - ~/.config/nvim
  - ~/.config/yay
  - ~/.config/zed
  - ~/.local/bin
  - ~/.scripts

mise:
nvim.init:
