require('mason-tool-installer').setup {

    -- a list of all tools you want to ensure are installed upon
    -- start; they should be the names Mason uses for each tool
    ensure_installed = {
        'prisma-language-server',
        'bash-language-server',
        'css-lsp',
        'dockerfile-language-server',
        'editorconfig-checker',
        'eslint-lsp',
        'html-lsp',
        'htmlbeautifier',
        'jq',
        'json-lsp',
        'jsonlint',
        'lua-language-server',
        'markdownlint',
        'prettier',
        -- 'ruby-lsp',
        'rust-analyzer',
        'shellcheck',
        'shfmt',
        'sql-formatter',
        { 'standardrb', version = '1.29.0' },
        'stylelint',
        'stylelint-lsp',
        'tailwindcss-language-server',
        'terraform-ls',
        'textlint',
        'ts_ls',
        'yaml-language-server',
        'yq',
    },
    auto_update = true,
}
